theme:
  name: material
repo_url: https://gitlab.com/example/python-app
copyright: Copyright &copy; 2024 The Python Sandbox Project

nav:
  - Home: index.md
  - User Guide: user-guide/README.md
  - Developer Guide: developer-guide/README.md
